import { useEffect, useRef, useState } from "react";
import { lookupBarcode } from "../../services/inventoryService";

function BarcodeScanner({ onBarcodeDetected }) {
  const videoRef = useRef(null); const frameRef = useRef(null); const [barcode,setBarcode]=useState(""); const [active,setActive]=useState(false); const [message,setMessage]=useState("");
  const stop = () => { cancelAnimationFrame(frameRef.current); videoRef.current?.srcObject?.getTracks().forEach((track)=>track.stop()); if(videoRef.current) videoRef.current.srcObject=null; setActive(false); };
  useEffect(()=>stop,[]);
  const apply = async (code) => { const value=code.trim(); if(!value)return setMessage("Enter or scan a barcode first."); setBarcode(value); try { const result=await lookupBarcode(value); onBarcodeDetected(value,result.found ? result.product : null); setMessage(result.found ? "Product details filled from your inventory. Review before saving." : "Barcode saved. Enter product details to continue."); } catch { onBarcodeDetected(value); setMessage("Barcode saved; product lookup is unavailable."); } };
  const start = async () => { if(!navigator.mediaDevices?.getUserMedia)return setMessage("Camera scanning is not supported by this browser."); try { const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}}}); videoRef.current.srcObject=stream; setActive(true); if(!("BarcodeDetector" in window)) return setMessage("Camera preview is available, but this browser cannot decode barcodes. Use manual entry or image upload."); const detector=new window.BarcodeDetector({formats:["code_128","ean_13","ean_8","qr_code","code_39","upc_a"]}); const scan=async()=>{if(!videoRef.current?.videoWidth)return frameRef.current=requestAnimationFrame(scan); try{const found=await detector.detect(videoRef.current);if(found[0]){stop();apply(found[0].rawValue);return;}}catch(error){console.debug("Barcode frame could not be decoded", error);} frameRef.current=requestAnimationFrame(scan);}; frameRef.current=requestAnimationFrame(scan); }catch{setMessage("Camera permission was denied or the camera is unavailable.");} };
  const image = async (event) => { const file=event.target.files?.[0]; if(!file)return; if(!("BarcodeDetector" in window))return setMessage("Image decoding needs a browser with BarcodeDetector support."); try { const bitmap=await createImageBitmap(file); const detector=new window.BarcodeDetector(); const found=await detector.detect(bitmap); if(found[0])apply(found[0].rawValue); else setMessage("No barcode or QR code was found in that image."); }catch{setMessage("Could not read that image.");} finally { event.target.value=""; } };
  return <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">Barcode / QR support</h3><div className="flex gap-2"><button type="button" onClick={active ? stop : start} className="rounded-md bg-slate-800 px-3 py-1.5 text-sm text-white">{active ? "Stop camera" : "Scan with camera"}</button><label className="cursor-pointer rounded-md border px-3 py-1.5 text-sm">Decode image<input type="file" accept="image/*" hidden onChange={image}/></label></div></div>{active && <video ref={videoRef} autoPlay playsInline muted className="mt-3 h-48 w-full rounded-lg bg-black object-cover"/>}<div className="mt-3 flex gap-2"><input value={barcode} onChange={(event)=>setBarcode(event.target.value)} placeholder="Enter barcode manually" className="min-w-0 flex-1 rounded-lg border border-slate-300 p-2"/><button type="button" onClick={()=>apply(barcode)} className="rounded-lg bg-cyan-700 px-4 text-sm text-white">Use code</button></div>{message && <p className="mt-2 text-sm text-slate-600">{message}</p>}</div>;
}
export default BarcodeScanner;
