import { useEffect, useState } from "react";
import { BrainCircuit, Package, Truck } from "lucide-react";
import DashboardLayout from "../../layouts/DashboardLayout";
import LogisticsPanel from "../../components/LogisticsPanel";
import { getInventory } from "../../services/inventoryService";

function Dashboard() {
  const [inventory, setInventory] = useState([]); const [showLogistics, setShowLogistics] = useState(false);
  useEffect(() => { getInventory().then((data) => setInventory(data.inventory || [])).catch(() => setInventory([])); }, []);
  const cards = [{ label: "Total inventory", value: inventory.length, icon: Package }, { label: "Surplus listings", value: "--", icon: Package }, { label: "Pending pickups", value: "--", icon: Truck, action: () => setShowLogistics(true) }];
  return <DashboardLayout title="Dashboard" role="Food Business"><div className="grid gap-5 md:grid-cols-3">{cards.map(({ label, value, icon: Icon, action }) => <button key={label} onClick={action} className={`rounded-lg border border-slate-800 bg-slate-900 p-5 text-left ${action ? "hover:border-emerald-500/60" : "cursor-default"}`}><Icon className="text-emerald-400" size={22} /><p className="mt-6 text-sm text-slate-400">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p>{action && <p className="mt-3 text-xs text-emerald-300">Open logistics availability</p>}</button>)}</div><div className="mt-7 grid gap-6 xl:grid-cols-2"><section className="rounded-lg border border-slate-800 bg-slate-900 p-6"><h2 className="font-semibold">Inventory activity</h2>{inventory.length ? <div className="mt-4 space-y-3">{inventory.slice(0, 5).map((item) => <div key={item.inventory_id} className="flex justify-between border-b border-slate-800 pb-3 text-sm"><span>{item.product_name}</span><span className="text-slate-400">{item.quantity} · expires {new Date(item.expiry_date).toLocaleDateString()}</span></div>)}</div> : <p className="mt-4 text-sm text-slate-400">Inventory activity will appear here after items are added.</p>}</section><section className="rounded-lg border border-cyan-500/20 bg-slate-900 p-6"><div className="flex items-center gap-2"><BrainCircuit className="text-cyan-300" size={21} /><h2 className="font-semibold">AI prediction</h2></div><p className="mt-4 text-sm leading-6 text-slate-400">Reserved for demand forecasts, expiry-risk alerts, and recommended surplus actions. Connect the AI service here when it is ready.</p><div className="mt-5 h-16 rounded border border-dashed border-slate-700" /></section></div>{showLogistics && <LogisticsPanel onClose={() => setShowLogistics(false)} />}</DashboardLayout>;
}
export default Dashboard;
