import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, RefreshCw } from "lucide-react";
import DashboardLayout from "../../layouts/DashboardLayout";
import { getExpiryAlerts } from "../../services/inventoryService";
import { subscribeToAiUpdates } from "../../services/aiUpdates";

const tierStyle = { high: "bg-red-500/15 text-red-200", medium: "bg-amber-500/15 text-amber-200", low: "bg-emerald-500/15 text-emerald-200" };

function ExpiryAlerts() {
  const [alerts, setAlerts] = useState([]);
  const [riskTier, setRiskTier] = useState("");
  const [sortBy, setSortBy] = useState("risk");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = useCallback(async () => { try { const response = await getExpiryAlerts(); setAlerts(response.alerts || []); setError(""); } catch { setError("Expiry alerts could not be loaded. Please try again."); } finally { setLoading(false); } }, []);
  useEffect(() => { const initial = setTimeout(load, 0); const unsubscribe = subscribeToAiUpdates(load); const interval = setInterval(load, 60000); return () => { clearTimeout(initial); unsubscribe(); clearInterval(interval); }; }, [load]);
  const visibleAlerts = useMemo(() => alerts.filter((alert) => !riskTier || alert.risk_tier === riskTier).sort((a, b) => sortBy === "days" ? a.days_to_expiry - b.days_to_expiry : Number(b.risk_score) - Number(a.risk_score)), [alerts, riskTier, sortBy]);

  return <DashboardLayout title="Expiry Alerts" role="Food Business"><div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">AI expiry alerts</h1><p className="mt-1 text-slate-400">Prioritize stock at risk of expiry using the latest AI scoring run.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-4 py-2.5 text-sm hover:bg-slate-800"><RefreshCw size={16} />Refresh</button></div><div className="grid gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4 sm:grid-cols-2"><label className="text-sm text-slate-400">Risk tier<select value={riskTier} onChange={(event) => setRiskTier(event.target.value)} className="mt-1 block w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-white"><option value="">All risk tiers</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label className="text-sm text-slate-400">Sort alerts<select value={sortBy} onChange={(event) => setSortBy(event.target.value)} className="mt-1 block w-full rounded-lg border border-slate-700 bg-slate-950 p-2.5 text-white"><option value="risk">Highest AI risk score</option><option value="days">Fewest days to expiry</option></select></label></div>{loading ? <p className="py-12 text-center text-slate-400">Loading AI expiry alerts…</p> : error ? <p className="rounded-lg border border-red-500/40 bg-red-500/10 p-4 text-red-100">{error}</p> : visibleAlerts.length ? <div className="overflow-x-auto rounded-xl border border-slate-800"><table className="min-w-full text-left text-sm"><thead className="bg-slate-900 text-slate-400"><tr>{["Item", "Days to expiry", "Alert threshold", "AI risk", "Recommended action"].map((heading) => <th className="px-4 py-3 font-medium" key={heading}>{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-800 bg-slate-950">{visibleAlerts.map((alert) => <tr key={alert.inventory_id}><td className="px-4 py-4"><p className="font-semibold">{alert.product_name}</p><p className="text-xs text-slate-400">{alert.category} · {alert.quantity} in stock</p></td><td className="px-4 py-4 font-semibold text-amber-200">{alert.days_to_expiry} day{alert.days_to_expiry === 1 ? "" : "s"}</td><td className="px-4 py-4">{alert.alert_days} days</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tierStyle[alert.risk_tier] || tierStyle.low}`}>{alert.risk_tier} · {Math.round(Number(alert.risk_score))}%</span></td><td className="max-w-sm px-4 py-4 text-slate-300">{alert.recommended_action}</td></tr>)}</tbody></table></div> : <div className="rounded-xl border border-dashed border-slate-700 p-12 text-center text-slate-400"><AlertTriangle className="mx-auto mb-3" size={28} /><p>No AI expiry alerts match these filters.</p></div>}</div></DashboardLayout>;
}

export default ExpiryAlerts;
