import { useEffect, useState } from "react";
import DashboardLayout from "../../layouts/DashboardLayout";
import api from "../../services/api";

function Profile() {
  const user = JSON.parse(localStorage.getItem("user") || "{}"); const isBusiness = user.role === "business";
  const [form, setForm] = useState({}); const [message, setMessage] = useState("");
  useEffect(() => { api.get(`/${isBusiness ? "business" : "ngo"}/profile`).then(({ data }) => setForm(data)).catch(() => setMessage("Unable to load your profile.")); }, [isBusiness]);
  const change = (e) => setForm((current) => ({ ...current, [e.target.name]: e.target.value }));
  const submit = async (e) => { e.preventDefault(); try { const { data } = await api.put(`/${isBusiness ? "business" : "ngo"}/profile`, form); const account = data.business || data.ngo; localStorage.setItem("user", JSON.stringify({ ...user, name: account.business_name || account.ngo_name, email: account.email })); setMessage("Profile updated."); } catch (error) { setMessage(error.response?.data?.message || "Could not update profile."); } };
  const fields = isBusiness ? [{ name: "business_name", label: "Business name" }, { name: "business_type", label: "Business type" }] : [{ name: "ngo_name", label: "NGO name" }, { name: "registration_number", label: "Registration number" }];
  return <DashboardLayout title="Profile settings" role={isBusiness ? "Food Business" : "Food Recipient Organization"}><form onSubmit={submit} className="max-w-3xl space-y-5 rounded-lg border border-slate-800 bg-slate-900 p-6"><div className="grid gap-4 md:grid-cols-2">{fields.map((field) => <label key={field.name} className="text-sm text-slate-300">{field.label}<input required name={field.name} value={form[field.name] || ""} onChange={change} className="mt-1 w-full rounded border border-slate-700 bg-slate-800 px-3 py-2 text-white" /></label>)}<label className="text-sm text-slate-300">Email<input disabled value={form.email || ""} className="mt-1 w-full rounded border border-slate-700 bg-slate-800 px-3 py-2 text-slate-400" /></label><label className="text-sm text-slate-300">Phone<input required name="phone" value={form.phone || ""} onChange={change} className="mt-1 w-full rounded border border-slate-700 bg-slate-800 px-3 py-2" /></label></div><label className="block text-sm text-slate-300">Address<input required name="address" value={form.address || ""} onChange={change} className="mt-1 w-full rounded border border-slate-700 bg-slate-800 px-3 py-2" /></label><div className="border-t border-slate-800 pt-5"><h2 className="font-semibold">Matching location</h2><p className="mt-1 text-sm text-slate-400">Coordinates enable distance-ranked partner matching. An AI/geocoding service can populate these later.</p><div className="mt-4 grid gap-4 md:grid-cols-3"><label className="text-sm text-slate-300">Latitude<input name="latitude" type="number" step="0.000001" value={form.latitude || ""} onChange={change} className="mt-1 w-full rounded border border-slate-700 bg-slate-800 px-3 py-2" /></label><label className="text-sm text-slate-300">Longitude<input name="longitude" type="number" step="0.000001" value={form.longitude || ""} onChange={change} className="mt-1 w-full rounded border border-slate-700 bg-slate-800 px-3 py-2" /></label><label className="text-sm text-slate-300">Service radius (km)<input name="service_radius_km" type="number" min="1" value={form.service_radius_km || 20} onChange={change} className="mt-1 w-full rounded border border-slate-700 bg-slate-800 px-3 py-2" /></label></div></div><button className="rounded bg-emerald-500 px-4 py-2 font-semibold hover:bg-emerald-600">Save profile</button>{message && <p className="text-sm text-emerald-300">{message}</p>}</form></DashboardLayout>;
}
export default Profile;
